// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace TodoApp.WebAPI.Persistence.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CreateAssignmentTable1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateAssignmentTable1));
        
        string IMigrationMetadata.Id
        {
            get { return "201807191009301_CreateAssignmentTable1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
